StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{5E101C543413F9D1}" {
   Id "CEN_Medical-Item_Epinephrine_Description"
   Target_en_us "Administered to unconscious patients, speeding up the wake-up process."
   Modified 1578127859
   Author "kexanone"
   LastChanged "kexanone"
  }
  CustomStringTableItem "{5E101C5587964B76}" {
   Id "CEN_Medical-Item_Epinephrine_Name"
   Target_en_us "Epinephrine Injector"
   Modified 1578127544
   Author "kexanone"
   LastChanged "kexanone"
  }
  CustomStringTableItem "{5E101C5589E004EE}" {
   Id "CEN_Medical-Item_Morphine_Description"
   Target_en_us "Administered to patients in strong pain."
   Modified 1578127876
   Author "kexanone"
   LastChanged "kexanone"
  }
 }
}